### ISSUE TITLE
Discussion on training the network and reproducing the result

### ISSUE THREAD

**Issue by xiaofeinot** [researchmm/TracKit#62]
Based on my own experience, I think tracking networks are usually more difficult to train and converge than other kind of networks. For example, from https://github.com/STVIR/pysot/discussions/437, we can see that the num of GPU can affect the batchsize and the final result. But in a "poor" laboratory, I don't have 8 GPUs to train my network, and maybe that's one reason why I always get a lower eao. So, how about you guys? Do you have any advice on how to train Siam Networks or reproduce the paper result?

**Comment by xiaofeinot** [comment]
All suggestions are welcome! Thank you!

**Comment by JudasDie** [comment]
> Based on my own experience, I think tracking networks are usually more difficult to train and converge than other kind of networks. For example, from [STVIR/pysot#437](https://github.com/STVIR/pysot/discussions/437), we can see that the num of GPU can affect the batchsize and the final result. But in a "poor" laboratory, I don't have 8 GPUs to train my network, and maybe that's one reason why I always get a lower eao. So, how about you guys? Do you have any advice on how to train Siam Networks or reproduce the paper result?

Hi, here are my experiences. The validation is suggested to apply on a "stable" benchmark, e.g., OTB, GOT10KVAL,VOT2020. As presented in VOT2020 challenge paper, the previous evaluation method, i.e. re-start, is truly sensitive to where to restart, or other words, hyper-parameters. It is thus not a wise choice to use them as validation. VOT2020 provides a really surprisingly stable protocol, you can try that. In my experience, the parameters on VOT2019, OTB, GO10K, LASOT perform similar on VOT2020,   Yet it is time-consuming since VOT2020 will run your model back and forth.  You may try to adjust your hyper-parameters in GOT10KVAL and then test on GOT10KTEST or VOT2020. And remember that, the best epoch on GOT10KVAL doesn't guarantee the corresponding best performance on GOT10KTEST. You may try to test the best five epochs on GOT10K online server. As for GPU numbers,  4 GPUs with each hosting 32 images can achieve a good result (I haven't try PYSOT and cannot guarantee that repo). Last but not the least, pls tune the hyper-parameters if you try to reproduce VOT with Siamese network. VOT2019 is less sensitive, you may try that. If you want to get more experience, you may watch my videos on Bilibili (search 张志鹏).
